version: '3'

services:
  db: 
    image: postgres:14.4
    container_name: anylistDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_NAME}

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    volumes:
    - ./db/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - 8080:80
    depends_on:
      - db


